preprocessing:
  build_graphs:
    used_method: default
    use_all_files: True
    mimicry_edge_num: 0
    time_window_size: 60.0
    use_hashed_label: False
    fuse_edge: True
    node_label_features:
      subject: type, path, cmd_line
      file: type, path
      netflow: type, remote_ip, remote_port
    multi_dataset: none
  transformation:
    used_methods: none

featurization:
  feat_training:
    emb_dim: 128
    epochs: 50
    training_split: train
    use_seed: True
    used_method: word2vec
    word2vec:
      alpha: 0.025
      window_size: 5
      min_count: 1
      use_skip_gram: True
      num_workers: 1
      compute_loss: True
      negative: 5
      decline_rate: 30
  feat_inference:
    to_remove: True

detection:
  graph_preprocessing:
    save_on_disk: False
    node_features: node_emb,node_type
    edge_features: edge_type
    fix_buggy_graph_reindexer: False
    global_batching:
      used_method: none
    intra_graph_batching:
      used_methods: edges
      edges:
        intra_graph_batch_size: 1024
    inter_graph_batching:
      used_method: none
  gnn_training:
    used_method: default
    use_seed: True
    seed: 0
    deterministic: False
    num_epochs: 12
    patience: 3
    lr: 0.0001
    weight_decay: 0.00001
    node_hid_dim: 128
    node_out_dim: 128
    grad_accumulation: 1
    encoder:
      dropout: 0.3
      used_methods: hypformer
      x_is_tuple: True
      hypformer:
        trans_num_layers: 2
        trans_num_heads: 4
        trans_use_bn: True
        trans_use_residual: True
        trans_use_weight: True
        trans_use_act: True
        k_in: 1.0
        k_out: 1.0
        decoder_type: hyp
        add_positional_encoding: False
        attention_type: full
        power_k: 2
        trans_heads_concat: False
    decoder:
      used_methods: reconstruct_node_features
      reconstruct_node_features:
        loss: MSE
        decoder: node_mlp
        node_mlp:
          architecture_str: none
      use_few_shot: False

  evaluation:
    viz_malicious_nodes: False
    ground_truth_version: orthrus
    best_model_selection: best_adp
    used_method: node_evaluation
    node_evaluation:
      threshold_method: max_val_loss
      use_dst_node_loss: True
      use_kmeans: False
      kmeans_top_K: 30
